pipeline: add checking snapshot to pipeline

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -18,10 +18,27 @@ jobs:
     - name: Install Playwright Browsers
       run: pnpm exec playwright install --with-deps
     - name: Run Playwright tests
-      run: pnpm exec playwright test
+      run: |
+        pnpm exec playwright test | tee output.log
+        if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
+          echo "Playwright tests failed due to snapshot difference."
+          echo "SNAPSHOT_DIFFERENT=true" >> $GITHUB_ENV
+          exit 1
+        elif grep -q "failed" output.log; then
+          echo "Playwright tests failed due to other reasons."
+          exit 1
+        fi
     - uses: actions/upload-artifact@v4
-      if: ${{ !cancelled() }}
+      if: always()
       with:
         name: playwright-report
         path: playwright-report/
         retention-days: 30
+    - name: Comment on Pull Request with report
+      uses: thollander/actions-comment-pull-request@v3
+      if: ${{ failure() && env.SNAPSHOT_DIFFERENT == 'true' }}
+      with:
+        message: |
+          ### Playwright visual snapshot differences were detected.
+          View the [Playwright report](${{ steps.artifact-upload.outputs.artifact-url }}) to review the visual differences.
+          **To approve the snapshot changes and update the snapshots, please comment:** /approve-snapshots
